name: Update daily-live manifest
on:
  schedule:
    - cron: "0 12,18 * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: daily-live

      - name: update manifest files
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/update.sh"
          "${GITHUB_WORKSPACE}/.github/update.sh"

      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update daily-live manifest
